// Catálogo simulado de productos agregados desde múltiples tiendas.
// En una versión productiva, estos datos vendrían de scrapers/APIs en tiempo real.
const CATALOG = [
  // Audio
  { id: 1, name: "Audífonos Sony WH-1000XM5", brand: "Sony", category: "audio",
    price: 329, rating: 4.8, reviews: 15420, store: "Amazon",
    url: "https://www.amazon.com/s?k=sony+wh-1000xm5",
    keywords: ["audífonos", "headphones", "inalámbricos", "bluetooth", "ruido", "sony"] },
  { id: 2, name: "Audífonos Sony WH-CH520", brand: "Sony", category: "audio",
    price: 49, rating: 4.4, reviews: 8900, store: "MercadoLibre",
    url: "https://www.mercadolibre.com/search?q=sony+wh-ch520",
    keywords: ["audífonos", "inalámbricos", "bluetooth", "sony", "económicos"] },
  { id: 3, name: "Bose QuietComfort 45", brand: "Bose", category: "audio",
    price: 279, rating: 4.7, reviews: 9300, store: "BestBuy",
    url: "https://www.bestbuy.com/site/searchpage.jsp?st=bose+qc45",
    keywords: ["audífonos", "inalámbricos", "bluetooth", "ruido", "bose"] },
  { id: 4, name: "Audífonos JBL Tune 510BT", brand: "JBL", category: "audio",
    price: 39, rating: 4.3, reviews: 21000, store: "AliExpress",
    url: "https://www.aliexpress.com/wholesale?SearchText=jbl+tune+510bt",
    keywords: ["audífonos", "inalámbricos", "bluetooth", "jbl", "baratos"] },
  { id: 5, name: "AirPods Pro 2 (USB-C)", brand: "Apple", category: "audio",
    price: 229, rating: 4.8, reviews: 32000, store: "Apple Store",
    url: "https://www.apple.com/shop/buy-airpods/airpods-pro",
    keywords: ["audífonos", "apple", "airpods", "inalámbricos", "ruido"] },

  // Cómputo
  { id: 10, name: "Laptop Lenovo IdeaPad 3 15", brand: "Lenovo", category: "computo",
    price: 429, rating: 4.3, reviews: 4200, store: "Amazon",
    url: "https://www.amazon.com/s?k=lenovo+ideapad+3",
    keywords: ["laptop", "notebook", "estudiar", "oficina", "lenovo"] },
  { id: 11, name: "MacBook Air M3 13\"", brand: "Apple", category: "computo",
    price: 1099, rating: 4.9, reviews: 7800, store: "Apple Store",
    url: "https://www.apple.com/shop/buy-mac/macbook-air",
    keywords: ["laptop", "macbook", "apple", "m3", "estudiar", "trabajo"] },
  { id: 12, name: "ASUS VivoBook 15 Ryzen 5", brand: "ASUS", category: "computo",
    price: 549, rating: 4.4, reviews: 5100, store: "Newegg",
    url: "https://www.newegg.com/p/pl?d=asus+vivobook+15",
    keywords: ["laptop", "asus", "vivobook", "estudiar", "ryzen"] },
  { id: 13, name: "Dell XPS 13 Plus", brand: "Dell", category: "computo",
    price: 1299, rating: 4.6, reviews: 3400, store: "Dell",
    url: "https://www.dell.com/en-us/shop/dell-laptops/sr/laptops/xps-laptops",
    keywords: ["laptop", "dell", "xps", "trabajo", "premium"] },
  { id: 14, name: "Chromebook HP 14", brand: "HP", category: "computo",
    price: 249, rating: 4.1, reviews: 6200, store: "Walmart",
    url: "https://www.walmart.com/search?q=hp+chromebook+14",
    keywords: ["laptop", "chromebook", "estudiar", "económica", "hp"] },

  // Hogar
  { id: 20, name: "Aspiradora Robot Roomba j7+", brand: "iRobot", category: "hogar",
    price: 599, rating: 4.6, reviews: 8700, store: "Amazon",
    url: "https://www.amazon.com/s?k=roomba+j7",
    keywords: ["aspiradora", "robot", "hogar", "limpieza", "roomba"] },
  { id: 21, name: "Aspiradora Xiaomi Robot E10", brand: "Xiaomi", category: "hogar",
    price: 179, rating: 4.4, reviews: 12400, store: "AliExpress",
    url: "https://www.aliexpress.com/wholesale?SearchText=xiaomi+robot+e10",
    keywords: ["aspiradora", "robot", "xiaomi", "hogar", "limpieza", "económica"] },
  { id: 22, name: "Cafetera Nespresso Vertuo Next", brand: "Nespresso", category: "hogar",
    price: 159, rating: 4.5, reviews: 4400, store: "Target",
    url: "https://www.target.com/s?searchTerm=nespresso+vertuo",
    keywords: ["cafetera", "nespresso", "café", "hogar"] },
  { id: 23, name: "Licuadora Oster 14 Velocidades", brand: "Oster", category: "hogar",
    price: 39, rating: 4.2, reviews: 5600, store: "Walmart",
    url: "https://www.walmart.com/search?q=licuadora+oster",
    keywords: ["licuadora", "oster", "cocina", "hogar", "económica"] },

  // Deporte
  { id: 30, name: "Smartwatch Garmin Forerunner 265", brand: "Garmin", category: "deporte",
    price: 449, rating: 4.7, reviews: 3800, store: "REI",
    url: "https://www.rei.com/search?q=garmin+forerunner+265",
    keywords: ["smartwatch", "reloj", "correr", "garmin", "deporte"] },
  { id: 31, name: "Apple Watch SE (2da gen)", brand: "Apple", category: "deporte",
    price: 249, rating: 4.7, reviews: 22100, store: "Amazon",
    url: "https://www.amazon.com/s?k=apple+watch+se",
    keywords: ["smartwatch", "apple", "watch", "deporte", "reloj"] },
  { id: 32, name: "Xiaomi Smart Band 8", brand: "Xiaomi", category: "deporte",
    price: 39, rating: 4.4, reviews: 18800, store: "AliExpress",
    url: "https://www.aliexpress.com/wholesale?SearchText=xiaomi+band+8",
    keywords: ["smartband", "xiaomi", "reloj", "deporte", "económico"] },
  { id: 33, name: "Bicicleta Trek FX 3 Disc", brand: "Trek", category: "deporte",
    price: 899, rating: 4.8, reviews: 1200, store: "Trek",
    url: "https://www.trekbikes.com/us/en_US/bikes/hybrid-bikes/fitness-bikes/fx/",
    keywords: ["bicicleta", "trek", "ciclismo", "deporte"] },

  // Moda
  { id: 40, name: "Zapatillas Nike Pegasus 40", brand: "Nike", category: "moda",
    price: 130, rating: 4.7, reviews: 9200, store: "Nike",
    url: "https://www.nike.com/w?q=pegasus+40",
    keywords: ["zapatillas", "tenis", "nike", "correr", "running"] },
  { id: 41, name: "Zapatillas Adidas Ultraboost Light", brand: "Adidas", category: "moda",
    price: 190, rating: 4.6, reviews: 5800, store: "Adidas",
    url: "https://www.adidas.com/us/search?q=ultraboost+light",
    keywords: ["zapatillas", "tenis", "adidas", "ultraboost", "running"] },
  { id: 42, name: "Zapatillas Decathlon Kalenji Run", brand: "Decathlon", category: "moda",
    price: 29, rating: 4.2, reviews: 4400, store: "Decathlon",
    url: "https://www.decathlon.com/search?q=kalenji+run",
    keywords: ["zapatillas", "running", "correr", "decathlon", "económicas"] },
];
